name: geny
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1

# ===[Dependencies]===

dependencies:
  flutter:
    sdk: flutter

  # ---Specific Build Packages---
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ---Flutter Lints---

  flutter_lints: ^5.0.0



#===[Specific to Flutter packages]===
flutter:

  # ---Material icon---

  uses-material-design: true

  # ---Assets---
  assets:
    - assets/data/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
